id: I7A8F0F2B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:30:08+00:00'
last_modified: '2022-06-07T11:37:01.767332+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14700
  title: བཀའ་འགྱུར། ༼རྒྱལ་རྩེ་ཐེམ་སྤང་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B0D5:
      image_group_id: I1KG86226
      title: ''
      total_pages: 702
      order: 1
      base_file: B0D5.txt
    '1996':
      image_group_id: I1KG86227
      title: ''
      total_pages: 758
      order: 2
      base_file: 1996.txt
    9B28:
      image_group_id: I1KG86228
      title: ''
      total_pages: 774
      order: 3
      base_file: 9B28.txt
    C33D:
      image_group_id: I1KG86229
      title: ''
      total_pages: 708
      order: 4
      base_file: C33D.txt
    19C6:
      image_group_id: I1KG86230
      title: ''
      total_pages: 698
      order: 5
      base_file: 19C6.txt
    70C3:
      image_group_id: I1KG86231
      title: ''
      total_pages: 764
      order: 6
      base_file: 70C3.txt
    C9B1:
      image_group_id: I1KG86232
      title: ''
      total_pages: 778
      order: 7
      base_file: C9B1.txt
    '1814':
      image_group_id: I1KG86233
      title: ''
      total_pages: 738
      order: 8
      base_file: 1814.txt
    93A9:
      image_group_id: I1KG86234
      title: ''
      total_pages: 720
      order: 9
      base_file: 93A9.txt
    B22B:
      image_group_id: I1KG86235
      title: ''
      total_pages: 782
      order: 10
      base_file: B22B.txt
    1FDE:
      image_group_id: I1KG86236
      title: ''
      total_pages: 748
      order: 11
      base_file: 1FDE.txt
    A9E5:
      image_group_id: I1KG86237
      title: ''
      total_pages: 740
      order: 12
      base_file: A9E5.txt
    99ED:
      image_group_id: I1KG86238
      title: ''
      total_pages: 722
      order: 13
      base_file: 99ED.txt
    '2224':
      image_group_id: I1KG86239
      title: ''
      total_pages: 740
      order: 14
      base_file: 2224.txt
    4FA4:
      image_group_id: I1KG86240
      title: ''
      total_pages: 650
      order: 15
      base_file: 4FA4.txt
    A088:
      image_group_id: I1KG86241
      title: ''
      total_pages: 758
      order: 16
      base_file: A088.txt
    FC99:
      image_group_id: I1KG86242
      title: ''
      total_pages: 682
      order: 17
      base_file: FC99.txt
    01EA:
      image_group_id: I1KG86243
      title: ''
      total_pages: 676
      order: 18
      base_file: 01EA.txt
    42F9:
      image_group_id: I1KG86244
      title: ''
      total_pages: 696
      order: 19
      base_file: 42F9.txt
    DE8C:
      image_group_id: I1KG86245
      title: ''
      total_pages: 664
      order: 20
      base_file: DE8C.txt
    D69D:
      image_group_id: I1KG86246
      title: ''
      total_pages: 736
      order: 21
      base_file: D69D.txt
    E503:
      image_group_id: I1KG86247
      title: ''
      total_pages: 654
      order: 22
      base_file: E503.txt
    EF0A:
      image_group_id: I1KG86248
      title: ''
      total_pages: 720
      order: 23
      base_file: EF0A.txt
    1EFA:
      image_group_id: I1KG86249
      title: ''
      total_pages: 696
      order: 24
      base_file: 1EFA.txt
    4B4F:
      image_group_id: I1KG86250
      title: ''
      total_pages: 702
      order: 25
      base_file: 4B4F.txt
    '3924':
      image_group_id: I1KG86251
      title: ''
      total_pages: 682
      order: 26
      base_file: 3924.txt
    43F6:
      image_group_id: I1KG86252
      title: ''
      total_pages: 652
      order: 27
      base_file: 43F6.txt
    B155:
      image_group_id: I1KG86253
      title: ''
      total_pages: 670
      order: 28
      base_file: B155.txt
    931A:
      image_group_id: I1KG86254
      title: ''
      total_pages: 692
      order: 29
      base_file: 931A.txt
    D7A2:
      image_group_id: I1KG86255
      title: ''
      total_pages: 660
      order: 30
      base_file: D7A2.txt
    B503:
      image_group_id: I1KG86256
      title: ''
      total_pages: 730
      order: 31
      base_file: B503.txt
    D7BD:
      image_group_id: I1KG86257
      title: ''
      total_pages: 708
      order: 32
      base_file: D7BD.txt
    10AF:
      image_group_id: I1KG86258
      title: ''
      total_pages: 768
      order: 33
      base_file: 10AF.txt
    B788:
      image_group_id: I1KG86259
      title: ''
      total_pages: 728
      order: 34
      base_file: B788.txt
    E818:
      image_group_id: I1KG86260
      title: ''
      total_pages: 706
      order: 35
      base_file: E818.txt
    8F9B:
      image_group_id: I1KG86261
      title: ''
      total_pages: 764
      order: 36
      base_file: 8F9B.txt
    500C:
      image_group_id: I1KG86262
      title: ''
      total_pages: 720
      order: 37
      base_file: 500C.txt
    D72E:
      image_group_id: I1KG86263
      title: ''
      total_pages: 528
      order: 38
      base_file: D72E.txt
    '2202':
      image_group_id: I1KG86264
      title: ''
      total_pages: 512
      order: 39
      base_file: 2202.txt
    7C46:
      image_group_id: I1KG86265
      title: ''
      total_pages: 0
      order: 40
      base_file: 7C46.txt
    591A:
      image_group_id: I1KG86266
      title: ''
      total_pages: 0
      order: 41
      base_file: 591A.txt
    04FF:
      image_group_id: I1KG86267
      title: ''
      total_pages: 652
      order: 42
      base_file: 04FF.txt
    4B03:
      image_group_id: I1KG86268
      title: ''
      total_pages: 634
      order: 43
      base_file: 4B03.txt
    125F:
      image_group_id: I1KG86269
      title: ''
      total_pages: 654
      order: 44
      base_file: 125F.txt
    '1885':
      image_group_id: I1KG86270
      title: ''
      total_pages: 650
      order: 45
      base_file: 1885.txt
    '4921':
      image_group_id: I1KG86271
      title: ''
      total_pages: 664
      order: 46
      base_file: 4921.txt
    '3602':
      image_group_id: I1KG86272
      title: ''
      total_pages: 562
      order: 47
      base_file: 3602.txt
    11FF:
      image_group_id: I1KG86273
      title: ''
      total_pages: 732
      order: 48
      base_file: 11FF.txt
    43A8:
      image_group_id: I1KG86274
      title: ''
      total_pages: 638
      order: 49
      base_file: 43A8.txt
    1AF5:
      image_group_id: I1KG86275
      title: ''
      total_pages: 772
      order: 50
      base_file: 1AF5.txt
    9C43:
      image_group_id: I1KG86276
      title: ''
      total_pages: 826
      order: 51
      base_file: 9C43.txt
    BBBB:
      image_group_id: I1KG86277
      title: ''
      total_pages: 822
      order: 52
      base_file: BBBB.txt
    C9C5:
      image_group_id: I1KG86278
      title: ''
      total_pages: 824
      order: 53
      base_file: C9C5.txt
    D0E1:
      image_group_id: I1KG86279
      title: ''
      total_pages: 910
      order: 54
      base_file: D0E1.txt
    4F59:
      image_group_id: I1KG86280
      title: ''
      total_pages: 742
      order: 55
      base_file: 4F59.txt
    F6F2:
      image_group_id: I1KG86281
      title: ''
      total_pages: 0
      order: 56
      base_file: F6F2.txt
    073A:
      image_group_id: I1KG86282
      title: ''
      total_pages: 698
      order: 57
      base_file: 073A.txt
    242D:
      image_group_id: I1KG86283
      title: ''
      total_pages: 716
      order: 58
      base_file: 242D.txt
    B8FD:
      image_group_id: I1KG86284
      title: ''
      total_pages: 728
      order: 59
      base_file: B8FD.txt
    237F:
      image_group_id: I1KG86285
      title: ''
      total_pages: 724
      order: 60
      base_file: 237F.txt
    50DA:
      image_group_id: I1KG86286
      title: ''
      total_pages: 828
      order: 61
      base_file: 50DA.txt
    '3425':
      image_group_id: I1KG86287
      title: ''
      total_pages: 760
      order: 62
      base_file: 3425.txt
    B7B9:
      image_group_id: I1KG86288
      title: ''
      total_pages: 706
      order: 63
      base_file: B7B9.txt
    ABEB:
      image_group_id: I1KG86289
      title: ''
      total_pages: 726
      order: 64
      base_file: ABEB.txt
    F04F:
      image_group_id: I1KG86290
      title: ''
      total_pages: 738
      order: 65
      base_file: F04F.txt
    C47F:
      image_group_id: I1KG86291
      title: ''
      total_pages: 668
      order: 66
      base_file: C47F.txt
    '2310':
      image_group_id: I1KG86292
      title: ''
      total_pages: 760
      order: 67
      base_file: 2310.txt
    453D:
      image_group_id: I1KG86293
      title: ''
      total_pages: 702
      order: 68
      base_file: 453D.txt
    '1870':
      image_group_id: I1KG86294
      title: ''
      total_pages: 710
      order: 69
      base_file: 1870.txt
    B593:
      image_group_id: I1KG86295
      title: ''
      total_pages: 722
      order: 70
      base_file: B593.txt
    FEE9:
      image_group_id: I1KG86296
      title: ''
      total_pages: 728
      order: 71
      base_file: FEE9.txt
    C16A:
      image_group_id: I1KG86297
      title: ''
      total_pages: 738
      order: 72
      base_file: C16A.txt
    CCCA:
      image_group_id: I1KG86298
      title: ''
      total_pages: 762
      order: 73
      base_file: CCCA.txt
    85BB:
      image_group_id: I1KG86299
      title: ''
      total_pages: 746
      order: 74
      base_file: 85BB.txt
    E85B:
      image_group_id: I1KG86300
      title: ''
      total_pages: 626
      order: 75
      base_file: E85B.txt
    '3203':
      image_group_id: I1KG86301
      title: ''
      total_pages: 732
      order: 76
      base_file: 3203.txt
    C081:
      image_group_id: I1KG86302
      title: ''
      total_pages: 678
      order: 77
      base_file: C081.txt
    '3626':
      image_group_id: I1KG86303
      title: ''
      total_pages: 692
      order: 78
      base_file: 3626.txt
    '3901':
      image_group_id: I1KG86304
      title: ''
      total_pages: 672
      order: 79
      base_file: 3901.txt
    20F0:
      image_group_id: I1KG86305
      title: ''
      total_pages: 766
      order: 80
      base_file: 20F0.txt
    '4044':
      image_group_id: I1KG86306
      title: ''
      total_pages: 682
      order: 81
      base_file: 4044.txt
    0E9D:
      image_group_id: I1KG86307
      title: ''
      total_pages: 720
      order: 82
      base_file: 0E9D.txt
    C2C1:
      image_group_id: I1KG86308
      title: ''
      total_pages: 698
      order: 83
      base_file: C2C1.txt
    075D:
      image_group_id: I1KG86309
      title: ''
      total_pages: 694
      order: 84
      base_file: 075D.txt
    E4ED:
      image_group_id: I1KG86310
      title: ''
      total_pages: 722
      order: 85
      base_file: E4ED.txt
    D44E:
      image_group_id: I1KG86311
      title: ''
      total_pages: 728
      order: 86
      base_file: D44E.txt
    F2C7:
      image_group_id: I1KG86312
      title: ''
      total_pages: 730
      order: 87
      base_file: F2C7.txt
    55EC:
      image_group_id: I1KG86313
      title: ''
      total_pages: 844
      order: 88
      base_file: 55EC.txt
    '4986':
      image_group_id: I1KG86314
      title: ''
      total_pages: 724
      order: 89
      base_file: 4986.txt
    D684:
      image_group_id: I1KG86315
      title: ''
      total_pages: 758
      order: 90
      base_file: D684.txt
    FC44:
      image_group_id: I1KG86316
      title: ''
      total_pages: 616
      order: 91
      base_file: FC44.txt
    8C7E:
      image_group_id: I1KG86317
      title: ''
      total_pages: 606
      order: 92
      base_file: 8C7E.txt
    E146:
      image_group_id: I1KG86318
      title: ''
      total_pages: 604
      order: 93
      base_file: E146.txt
    FFA4:
      image_group_id: I1KG86319
      title: ''
      total_pages: 846
      order: 94
      base_file: FFA4.txt
    E9E7:
      image_group_id: I1KG86320
      title: ''
      total_pages: 748
      order: 95
      base_file: E9E7.txt
    43AA:
      image_group_id: I1KG86321
      title: ''
      total_pages: 626
      order: 96
      base_file: 43AA.txt
    AA38:
      image_group_id: I1KG86322
      title: ''
      total_pages: 882
      order: 97
      base_file: AA38.txt
    95D5:
      image_group_id: I1KG86323
      title: ''
      total_pages: 836
      order: 98
      base_file: 95D5.txt
    E40E:
      image_group_id: I1KG86324
      title: ''
      total_pages: 768
      order: 99
      base_file: E40E.txt
    84F4:
      image_group_id: I1KG86325
      title: ''
      total_pages: 756
      order: 100
      base_file: 84F4.txt
    D032:
      image_group_id: I1KG86326
      title: ''
      total_pages: 828
      order: 101
      base_file: D032.txt
    D0AB:
      image_group_id: I1KG86327
      title: ''
      total_pages: 872
      order: 102
      base_file: D0AB.txt
    '4194':
      image_group_id: I1KG86328
      title: ''
      total_pages: 690
      order: 103
      base_file: 4194.txt
    '7957':
      image_group_id: I1KG86329
      title: ''
      total_pages: 718
      order: 104
      base_file: 7957.txt
    D57B:
      image_group_id: I1KG86330
      title: ''
      total_pages: 602
      order: 105
      base_file: D57B.txt
    60D8:
      image_group_id: I1KG86331
      title: ''
      total_pages: 788
      order: 106
      base_file: 60D8.txt
    6DA1:
      image_group_id: I1KG86332
      title: ''
      total_pages: 850
      order: 107
      base_file: 6DA1.txt
    2A6E:
      image_group_id: I1KG86333
      title: ''
      total_pages: 1032
      order: 108
      base_file: 2A6E.txt
    '6446':
      image_group_id: I1KG86334
      title: ''
      total_pages: 752
      order: 109
      base_file: 6446.txt
    A5CA:
      image_group_id: I1KG86335
      title: ''
      total_pages: 710
      order: 110
      base_file: A5CA.txt
    7A7D:
      image_group_id: I1KG86336
      title: ''
      total_pages: 970
      order: 111
      base_file: 7A7D.txt
    '4820':
      image_group_id: I1KG86337
      title: ''
      total_pages: 996
      order: 112
      base_file: 4820.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
