id: P000006
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14700
  title: བཀའ་འགྱུར། ༼རྒྱལ་རྩེ་ཐེམ་སྤང་མ།༽
  author: ''
  volumes:
    1d45f9f6c54a417fad4bda42391946da:
      image_group_id: I1KG86226
      title: ''
      volume_number: 1
      total_pages: 702
    11e0976bc0b247fe8f9c3f3e9436932a:
      image_group_id: I1KG86227
      title: ''
      volume_number: 2
      total_pages: 758
    df53f71a9ad54c4ea2b3e300b5b81a5c:
      image_group_id: I1KG86228
      title: ''
      volume_number: 3
      total_pages: 774
    f742dd107eeb4626aa9b5a2c678d5242:
      image_group_id: I1KG86229
      title: ''
      volume_number: 4
      total_pages: 708
    0827806c44a1434b8819c988d1e9dd41:
      image_group_id: I1KG86230
      title: ''
      volume_number: 5
      total_pages: 698
    fb1b5b553e72455fa763b4adef96fb14:
      image_group_id: I1KG86231
      title: ''
      volume_number: 6
      total_pages: 764
    90e81b6308354dac85ca788498c2507a:
      image_group_id: I1KG86232
      title: ''
      volume_number: 7
      total_pages: 778
    a2f46579ec74479cbb62f467d8ee354a:
      image_group_id: I1KG86233
      title: ''
      volume_number: 8
      total_pages: 738
    09f88ccfe0c143a3af85a4971144c1fb:
      image_group_id: I1KG86234
      title: ''
      volume_number: 9
      total_pages: 720
    0d21b93937404c36a43a4bbd59b8f4a0:
      image_group_id: I1KG86235
      title: ''
      volume_number: 10
      total_pages: 782
    8b08c37dce0d47d3af0edb79ed325433:
      image_group_id: I1KG86236
      title: ''
      volume_number: 11
      total_pages: 748
    41f8fcb08c6941d6baf94244efe1420c:
      image_group_id: I1KG86237
      title: ''
      volume_number: 12
      total_pages: 740
    f5a1a61fc79d4772b22d348590b528d1:
      image_group_id: I1KG86238
      title: ''
      volume_number: 13
      total_pages: 722
    ee8fd0d15f7743889c366f5c88ad8d4e:
      image_group_id: I1KG86239
      title: ''
      volume_number: 14
      total_pages: 740
    95df82204d9f4e228c0516e9bb0c4a18:
      image_group_id: I1KG86240
      title: ''
      volume_number: 15
      total_pages: 650
    8341a5c8ded84258ab8a906d0a04f95c:
      image_group_id: I1KG86241
      title: ''
      volume_number: 16
      total_pages: 758
    6e81fa56642c4427ab736588f89f3f13:
      image_group_id: I1KG86242
      title: ''
      volume_number: 17
      total_pages: 682
    483cb188c1724b44bb0efa424a58d9d1:
      image_group_id: I1KG86243
      title: ''
      volume_number: 18
      total_pages: 676
    5bd18f6ebbe94464bb4441b5cd5b1082:
      image_group_id: I1KG86244
      title: ''
      volume_number: 19
      total_pages: 696
    732643ec78334a7dbc6893909fa353fc:
      image_group_id: I1KG86245
      title: ''
      volume_number: 20
      total_pages: 664
    9459485d8a8f42e38b0f250f427be521:
      image_group_id: I1KG86246
      title: ''
      volume_number: 21
      total_pages: 736
    aebc51c8330d4c538bb893834ebb1d81:
      image_group_id: I1KG86247
      title: ''
      volume_number: 22
      total_pages: 654
    ea55a4629d08424781477756358d88c9:
      image_group_id: I1KG86248
      title: ''
      volume_number: 23
      total_pages: 720
    29ad0aee83494f2694b854891140cf03:
      image_group_id: I1KG86249
      title: ''
      volume_number: 24
      total_pages: 696
    6200dbd234a94372ab5f15dd38a5798c:
      image_group_id: I1KG86250
      title: ''
      volume_number: 25
      total_pages: 702
    585b580741d448a9a7e99f50f83f0def:
      image_group_id: I1KG86251
      title: ''
      volume_number: 26
      total_pages: 682
    d2682f2dc2284f20b2d45e502f035488:
      image_group_id: I1KG86252
      title: ''
      volume_number: 27
      total_pages: 652
    ac438e976f024a92ba0d9984c9052958:
      image_group_id: I1KG86253
      title: ''
      volume_number: 28
      total_pages: 670
    48671bb61d1644d196d33d5485e9aca8:
      image_group_id: I1KG86254
      title: ''
      volume_number: 29
      total_pages: 692
    f4a69b7491d14692b9baea1f8bc340de:
      image_group_id: I1KG86255
      title: ''
      volume_number: 30
      total_pages: 660
    2f1785dd02544a80be4c6e8fb37da531:
      image_group_id: I1KG86256
      title: ''
      volume_number: 31
      total_pages: 730
    2fd3bdc629b4487caff876eee638bca8:
      image_group_id: I1KG86257
      title: ''
      volume_number: 32
      total_pages: 708
    2586942166824e17ad22781a29eb051e:
      image_group_id: I1KG86258
      title: ''
      volume_number: 33
      total_pages: 768
    7c9ca3c7d4834d6f93b2c67fcd88635a:
      image_group_id: I1KG86259
      title: ''
      volume_number: 34
      total_pages: 728
    715aea2ce12645aa932fb6f37f210e87:
      image_group_id: I1KG86260
      title: ''
      volume_number: 35
      total_pages: 706
    2a7d6d6aef8b4c368e63fa53a28e1c91:
      image_group_id: I1KG86261
      title: ''
      volume_number: 36
      total_pages: 764
    050ff9fe29ea4841b09d49822d44afbd:
      image_group_id: I1KG86262
      title: ''
      volume_number: 37
      total_pages: 720
    2c0af51fbc684ad6b28431c496b2f315:
      image_group_id: I1KG86263
      title: ''
      volume_number: 38
      total_pages: 528
    8e7a70858d5a4f98be526b8230e1ce79:
      image_group_id: I1KG86264
      title: ''
      volume_number: 39
      total_pages: 512
    4507a431e6804064a4447142528e9deb:
      image_group_id: I1KG86265
      title: ''
      volume_number: 40
      total_pages: 0
    19ed3f96aa884f6698d762b98cb93432:
      image_group_id: I1KG86266
      title: ''
      volume_number: 41
      total_pages: 0
    d9ee3a28437f482dac0e2127e6a6d790:
      image_group_id: I1KG86267
      title: ''
      volume_number: 42
      total_pages: 652
    9eb08f9f734c4a90ad7307517f4b9a9e:
      image_group_id: I1KG86268
      title: ''
      volume_number: 43
      total_pages: 634
    cc4b91e8b625439b8275feddebd974c3:
      image_group_id: I1KG86269
      title: ''
      volume_number: 44
      total_pages: 654
    cbcbd4088b1749e6916e8ce63fc6dff3:
      image_group_id: I1KG86270
      title: ''
      volume_number: 45
      total_pages: 650
    b3aeff2c6b8a40a2af832e37cdb5c2f2:
      image_group_id: I1KG86271
      title: ''
      volume_number: 46
      total_pages: 664
    710d745baf9b4f5395021da946fa954f:
      image_group_id: I1KG86272
      title: ''
      volume_number: 47
      total_pages: 562
    42fd66000ef44437803a6bb6732d2888:
      image_group_id: I1KG86273
      title: ''
      volume_number: 48
      total_pages: 732
    b2638542c67e4a56896668e45f81a635:
      image_group_id: I1KG86274
      title: ''
      volume_number: 49
      total_pages: 638
    cd91bca786374be2b0fd8209bb24f5fd:
      image_group_id: I1KG86275
      title: ''
      volume_number: 50
      total_pages: 772
    e7ede9effe0b4344bd2c597e9a5c556e:
      image_group_id: I1KG86276
      title: ''
      volume_number: 51
      total_pages: 826
    2aff78f320e2489783b1f0471ea23a5f:
      image_group_id: I1KG86277
      title: ''
      volume_number: 52
      total_pages: 822
    e536668b440245c7a23d190ab3bb6c7f:
      image_group_id: I1KG86278
      title: ''
      volume_number: 53
      total_pages: 824
    457b7bd66f264a40bbe65e215c40af6c:
      image_group_id: I1KG86279
      title: ''
      volume_number: 54
      total_pages: 910
    13897a4d4b1a44c98fc076f9f2a061b9:
      image_group_id: I1KG86280
      title: ''
      volume_number: 55
      total_pages: 742
    44925e9ad0c84becbf968ce3c875ecd7:
      image_group_id: I1KG86281
      title: ''
      volume_number: 56
      total_pages: 0
    625d315cf9814f9cb4abf072fc305080:
      image_group_id: I1KG86282
      title: ''
      volume_number: 57
      total_pages: 698
    46b5e3e678d14efbb97f445983a7294b:
      image_group_id: I1KG86283
      title: ''
      volume_number: 58
      total_pages: 716
    c23f2550a7154a0da12bebd31548af7f:
      image_group_id: I1KG86284
      title: ''
      volume_number: 59
      total_pages: 728
    604e2b7cd5ac44069ede74e186dfa3b0:
      image_group_id: I1KG86285
      title: ''
      volume_number: 60
      total_pages: 724
    6380b68db6a84715b47d12bdb4c84e03:
      image_group_id: I1KG86286
      title: ''
      volume_number: 61
      total_pages: 828
    bfc8c4b4d61448e2823e5914c00d3523:
      image_group_id: I1KG86287
      title: ''
      volume_number: 62
      total_pages: 760
    1c1b3283c3ea48ac864f1dead9a5d83b:
      image_group_id: I1KG86288
      title: ''
      volume_number: 63
      total_pages: 706
    1fb2082b1600485088318008dd6b0717:
      image_group_id: I1KG86289
      title: ''
      volume_number: 64
      total_pages: 726
    8ec158925e6f4e2e9373d2023d0a7aea:
      image_group_id: I1KG86290
      title: ''
      volume_number: 65
      total_pages: 738
    4f34187197bb4527829cee9e703fdb82:
      image_group_id: I1KG86291
      title: ''
      volume_number: 66
      total_pages: 668
    14df03a4db044c0a85877a6baa136e7c:
      image_group_id: I1KG86292
      title: ''
      volume_number: 67
      total_pages: 760
    c05e3c07fed849e3b9acb817b737cec7:
      image_group_id: I1KG86293
      title: ''
      volume_number: 68
      total_pages: 702
    c72c786ef5194f93bc70ce5ab6368344:
      image_group_id: I1KG86294
      title: ''
      volume_number: 69
      total_pages: 710
    b6136128369c4229bd7bacbdda528439:
      image_group_id: I1KG86295
      title: ''
      volume_number: 70
      total_pages: 722
    cfd20ea299734e8bacb0256490a3c0af:
      image_group_id: I1KG86296
      title: ''
      volume_number: 71
      total_pages: 728
    f6c083dd819e45c9a8626551ec5f5504:
      image_group_id: I1KG86297
      title: ''
      volume_number: 72
      total_pages: 738
    d2604de888a4491dbdc20f19f4e9d902:
      image_group_id: I1KG86298
      title: ''
      volume_number: 73
      total_pages: 762
    6d66c2153e0342c496649282cee06bd9:
      image_group_id: I1KG86299
      title: ''
      volume_number: 74
      total_pages: 746
    46f329fdd23b41fd8b083ca297a37591:
      image_group_id: I1KG86300
      title: ''
      volume_number: 75
      total_pages: 626
    7368e696570e4dc6a0d6554a762708c4:
      image_group_id: I1KG86301
      title: ''
      volume_number: 76
      total_pages: 732
    6fbe75d993e041d08392fccea35436a1:
      image_group_id: I1KG86302
      title: ''
      volume_number: 77
      total_pages: 678
    8546756c1e6d4ac19de17245334b095c:
      image_group_id: I1KG86303
      title: ''
      volume_number: 78
      total_pages: 692
    b171c8af36a54252a91a624022c11add:
      image_group_id: I1KG86304
      title: ''
      volume_number: 79
      total_pages: 672
    6fc44b3779b7447f83314b214a6616bd:
      image_group_id: I1KG86305
      title: ''
      volume_number: 80
      total_pages: 766
    80a16dcc4b354a0ab93443f3abaef0da:
      image_group_id: I1KG86306
      title: ''
      volume_number: 81
      total_pages: 682
    9847cbb911834436af28892cad3eea75:
      image_group_id: I1KG86307
      title: ''
      volume_number: 82
      total_pages: 720
    4e48e62ec9f34ef885aa78b0acd6e3d0:
      image_group_id: I1KG86308
      title: ''
      volume_number: 83
      total_pages: 698
    c9e0ab5d6e7e47808dfdf2fc17f8f3cb:
      image_group_id: I1KG86309
      title: ''
      volume_number: 84
      total_pages: 694
    1b775ef2666047b1b93264f030368241:
      image_group_id: I1KG86310
      title: ''
      volume_number: 85
      total_pages: 722
    bfbfd4f2c7d14960befefa9308b2f968:
      image_group_id: I1KG86311
      title: ''
      volume_number: 86
      total_pages: 728
    4ee69574f8334487a8903c028f2df10a:
      image_group_id: I1KG86312
      title: ''
      volume_number: 87
      total_pages: 730
    f793671ba2f14137a12ace770f43a357:
      image_group_id: I1KG86313
      title: ''
      volume_number: 88
      total_pages: 844
    581d9d16616e4dd08b394e810cd1fd79:
      image_group_id: I1KG86314
      title: ''
      volume_number: 89
      total_pages: 724
    fd8a1609c409424c8c713e3c6930b8be:
      image_group_id: I1KG86315
      title: ''
      volume_number: 90
      total_pages: 758
    edfc3090bd994419ba096199afe40a97:
      image_group_id: I1KG86316
      title: ''
      volume_number: 91
      total_pages: 616
    6b653d611fca4c71ad2a89cfca25c13d:
      image_group_id: I1KG86317
      title: ''
      volume_number: 92
      total_pages: 606
    9be5af2469c4431a9b38a66031b14c30:
      image_group_id: I1KG86318
      title: ''
      volume_number: 93
      total_pages: 604
    1aa4842be24248dcb7e05d317dd3f66f:
      image_group_id: I1KG86319
      title: ''
      volume_number: 94
      total_pages: 846
    73b1a0ec5fa447a78ec7f31a32592cfa:
      image_group_id: I1KG86320
      title: ''
      volume_number: 95
      total_pages: 748
    0b35a4e12202433f86dd5ab6cb96ae75:
      image_group_id: I1KG86321
      title: ''
      volume_number: 96
      total_pages: 626
    417f6e26b5a4473eab56bf989c16251f:
      image_group_id: I1KG86322
      title: ''
      volume_number: 97
      total_pages: 882
    2ce85a90608e490bae520288372fc061:
      image_group_id: I1KG86323
      title: ''
      volume_number: 98
      total_pages: 836
    40c6745c2de9400392c3a32fc475f3ce:
      image_group_id: I1KG86324
      title: ''
      volume_number: 99
      total_pages: 768
    9f34314e1f2d4c74a7df665dc87b4399:
      image_group_id: I1KG86325
      title: ''
      volume_number: 100
      total_pages: 756
    a521773e7db248858c9255c25f7ac482:
      image_group_id: I1KG86326
      title: ''
      volume_number: 101
      total_pages: 828
    5251d6c4752746eda77e9ab90b3ba4bf:
      image_group_id: I1KG86327
      title: ''
      volume_number: 102
      total_pages: 872
    4cb6f7baa2bb41b7a8d1985899e095f5:
      image_group_id: I1KG86328
      title: ''
      volume_number: 103
      total_pages: 690
    1ab8615a07804d1a8f5bbce187cf4cca:
      image_group_id: I1KG86329
      title: ''
      volume_number: 104
      total_pages: 718
    971083e265cf4693aa1ca5fccf7df988:
      image_group_id: I1KG86330
      title: ''
      volume_number: 105
      total_pages: 602
    b19578055cdd4cd1bb4319eb3d518c2f:
      image_group_id: I1KG86331
      title: ''
      volume_number: 106
      total_pages: 788
    2ea55c27a07c43b78e99e2ea7499575a:
      image_group_id: I1KG86332
      title: ''
      volume_number: 107
      total_pages: 850
    6b9b2efc231c4af48542e0ce9b33d682:
      image_group_id: I1KG86333
      title: ''
      volume_number: 108
      total_pages: 1032
    78648f9a89f348518a90a27972386f1c:
      image_group_id: I1KG86334
      title: ''
      volume_number: 109
      total_pages: 752
    3204a2bc88b049e6a8dc539e8500af5d:
      image_group_id: I1KG86335
      title: ''
      volume_number: 110
      total_pages: 710
    ecde59fc9d484748a16e4ac0a84f8e76:
      image_group_id: I1KG86336
      title: ''
      volume_number: 111
      total_pages: 970
    b6b8b42a1ac04a35ae394752e976473a:
      image_group_id: I1KG86337
      title: ''
      volume_number: 112
      total_pages: 996
    e628ff5bbe944a1cabf2a087c31eb7b2:
      image_group_id: I1KG86338
      title: ''
      volume_number: 113
      total_pages: 746
    020f0b91ebf04a8f90b541856d34de59:
      image_group_id: I1KG86339
      title: ''
      volume_number: 114
      total_pages: 886
    dd564a548b484bbe95f53d86df8827e7:
      image_group_id: I1KG86340
      title: ''
      volume_number: 115
      total_pages: 445
